# Configuration file for custom scenarios for `premise`
# Energy Perspective Scenario 2050+
# https://www.bfe.admin.ch/bfe/en/home/policy/energy-perspectives-2050-plus.html/

---

production pathways:
  hydro_run_of_river:
    production volume:
      variable: Production|Electricity|Run-of-river hydro
    ecoinvent alias:
      name: electricity production, hydro, run-of-river
      reference product: electricity, high voltage
      exists in original database: True
 
  hydro_reservoir:
    production volume:
      variable: Production|Electricity|Reservoir
    ecoinvent alias:
      name: electricity production, hydro, reservoir, alpine region
      reference product: electricity, high voltage
      exists in original database: True

  nuclear_boiling_water:
    production volume:
      variable: Production|Electricity|Nuclear|Boiling water reactor
    ecoinvent alias:
      name: electricity production, nuclear, boiling water reactor
      reference product: electricity, high voltage
      exists in original database: True

  nuclear_pressure_water:
    production volume:
      variable: Production|Electricity|Nuclear|Pressure water reactor
    ecoinvent alias:
      name: electricity production, nuclear, pressure water reactor
      reference product: electricity, high voltage
      exists in original database: True

  conventional_waste:
    production volume:
      variable: Production|Electricity|Conventional|Waste-to-Energy
    ecoinvent alias:
      name: treatment of municipal solid waste, incineration
      reference product: electricity, for reuse in municipal waste incineration only
      exists in original database: True

  conventional_other:
    production volume:
      variable: Production|Electricity|Conventional|Other
    ecoinvent alias:
      name: electricity production, natural gas, combined cycle power plant
      reference product: electricity, high voltage
      exists in original database: True

  pv:
    production volume:
      variable: Production|Electricity|Renewable|Photovoltaic
    ecoinvent alias:
      name: electricity production, photovoltaic
      reference product: electricity, low voltage
      exists in original database: True

  wind:
    production volume:
      variable: Production|Electricity|Renewable|Wind turbines|Onshore
    ecoinvent alias:
      name: electricity production, wind, >3MW turbine, onshore, renewable energy products
      reference product: electricity, high voltage, renewable energy products
      exists in original database: True

  geothermal:
    production volume:
      variable: Production|Electricity|Renewable|Geothermal
    ecoinvent alias:
      name: electricity production, deep geothermal
      reference product: electricity, high voltage
      exists in original database: True

  biomass:
    production volume:
      variable: Production|Electricity|Renewable|Biomass
    ecoinvent alias:
      name: heat and power co-generation, wood chips, 6667 kW
      reference product: electricity, high voltage
      exists in original database: True

  biogas:
    production volume:
      variable: Production|Electricity|Renewable|Biogas
    ecoinvent alias:
      name: heat and power co-generation, biogas, gas engine
      reference product: electricity, high voltage
      exists in original database: True

  import:
    production volume:
      variable: Production|Electricity|Import
    ecoinvent alias:
      name: import from neighboring countries electricity, high voltage
      reference product: electricity, high voltage
      exists in original database: False
      new dataset: True

  medium_to_high:
    production volume:
      variable: Production|Electricity|Medium to high
    ecoinvent alias:
      name: market for electricity, high voltage, EP2050
      reference product: electricity, high voltage
      exists in original database: False
      new dataset: True

  low_to_medium:
    production volume:
      variable: Production|Electricity|Low to medium
    ecoinvent alias:
      name: market for electricity, medium voltage, EP2050
      reference product: electricity, medium voltage
      exists in original database: False
      new dataset: True

  neighbors_hydro_reservoir:
    production volume:
      variable: Production|Electricity|Neighbor countries|Reservoir
    ecoinvent alias:
      name: electricity production, hydro, reservoir, alpine region
      reference product: electricity, high voltage
      exists in original database: True

  neighbors_nuclear:
    production volume:
      variable: Production|Electricity|Neighbor countries|Nuclear
    ecoinvent alias:
      name: electricity production, nuclear, boiling water reactor
      reference product: electricity, high voltage
      exists in original database: True

  neighbors_coal:
    production volume:
      variable: Production|Electricity|Neighbor countries|Coal
    ecoinvent alias:
      name: electricity production, hard coal
      reference product: electricity, high voltage
      exists in original database: True

  neighbors_conventional_ng:
    production volume:
      variable: Production|Electricity|Neighbor countries|Natural gas
    ecoinvent alias:
      name: electricity production, natural gas, combined cycle power plant
      reference product: electricity, high voltage
      exists in original database: True

  neighbors_conventional_waste:
    production volume:
      variable: Production|Electricity|Neighbor countries|Conventional|Waste-to-Energy
    ecoinvent alias:
      name: treatment of municipal solid waste, incineration
      reference product: electricity, for reuse in municipal waste incineration only
      exists in original database: True

  neighbors_pv:
    production volume:
      variable: Production|Electricity|Neighbor countries|Renewable|Photovoltaic
    ecoinvent alias:
      name: electricity production, photovoltaic
      reference product: electricity, low voltage
      exists in original database: True

  neighbors_wind_on:
    production volume:
      variable: Production|Electricity|Neighbor countries|Renewable|Wind turbines|Onshore
    ecoinvent alias:
      name: electricity production, wind, >3MW turbine, onshore
      reference product: electricity, high voltage
      exists in original database: True

  neighbors_wind_off:
    production volume:
      variable: Production|Electricity|Neighbor countries|Renewable|Wind turbines|Offshore
    ecoinvent alias:
      name: electricity production, wind, 1-3MW turbine, offshore
      reference product: electricity, high voltage
      exists in original database: True
  
  neighbors_biomass:
    production volume:
      variable: Production|Electricity|Neighbor countries|Renewable|Biomass
    ecoinvent alias:
      name: heat and power co-generation, wood chips, 6667 kW
      reference product: electricity, high voltage
      exists in original database: True

  neighbors_import:
    production volume:
      variable: Production|Electricity|Neighbor countries|Import
    ecoinvent alias:
      name: market group for electricity, high voltage
      reference product: electricity, high voltage
      exists in original database: True
  

markets:

  - name: import from neighboring countries electricity, high voltage
    reference product: electricity, high voltage
    unit: kilowatt hour
    includes:
      - neighbors_hydro_reservoir
      - neighbors_nuclear
      - neighbors_coal
      - neighbors_conventional_ng
      - conventional_waste
      - neighbors_pv
      - neighbors_wind_on
      - neighbors_wind_off
      - neighbors_biomass
      - neighbors_import
    
    except regions:
      - World

  - name: market for electricity, high voltage, EP2050
    reference product: electricity, high voltage
    unit: kilowatt hour
    includes:
      - hydro_run_of_river
      - hydro_reservoir
      - nuclear_boiling_water
      - nuclear_pressure_water
      - conventional_waste
      - conventional_other
      - pv
      - wind
      - geothermal
      - biomass
      - biogas
      - import

    add:

      - name: transmission network construction, long-distance
        reference product: transmission network, long-distance
        amount: 3.17e-10

      - name: transmission network construction, electricity, high voltage
        reference product: transmission network, electricity, high voltage
        amount: 6.58e-09

      - name: Dinitrogen monoxide
        categories: air::unspecified
        amount: 5.0e-06

      - name: Ozone
        categories: air::unspecified
        amount: 4.16e-06

    replaces:
      - name: market for electricity, high voltage
        reference product: electricity, high voltage

    replaces in:
      - location: CH

    except regions:
      - World

  - name: market for electricity, medium voltage, EP2050
    reference product: electricity, medium voltage
    unit: kilowatt hour
    includes:
      - medium_to_high

    add:
      - name: market for sulfur hexafluoride, liquid
        reference product: sulfur hexafluoride, liquid
        amount: 5.4e-08

      - name: transmission network construction, electricity, medium voltage
        reference product: transmission network, electricity, medium voltage
        amount: 1.86e-08

      - name: Sulfur hexafluoride
        categories: air::unspecified
        amount: 5.4e-08

    efficiency:
      - variable: Transmission losses|Electricity|Medium to high

    replaces:
      - name: market for electricity, medium voltage
        reference product: electricity, medium voltage

    replaces in:
      - location: CH

    except regions:
      - World

  - name: market for electricity, low voltage, EP2050
    reference product: electricity, low voltage
    unit: kilowatt hour
    includes:
      - low_to_medium

    add:
      - name: market for sulfur hexafluoride, liquid
        reference product: sulfur hexafluoride, liquid
        amount: 2.99e-09

      - name: distribution network construction, electricity, low voltage
        reference product: distribution network, electricity, low voltage
        amount: 8.74e-08

      - name: Sulfur hexafluoride
        categories: air::unspecified
        amount: 2.99e-09

    efficiency:
      - variable: Distribution losses|Electricity|Low to medium

    replaces:
      - name: market for electricity, low voltage
        reference product: electricity, low voltage

    replaces in:
      - location: CH

    except regions:
      - World

  


  

  
  



  
